[size]
width = 3.4
ratio = 1.618

[color]
c1 = "#5759aa"  # blue
c2 = "#9c4c36" # red
# https://meyerweb.com/eric/tools/color-blend/#9C4C36:000000:9:hex
c1k = "#3F417C" #"#47498B"  # blue 30% black
c2k = "#803E2C" #"#7D3D2B"  # red 30% black
c3 = "#800080"  # purple https://www.rapidtables.com/web/color/purple-color.html
c4 = "#9400D3"  # darkviolet
alpha = 0.5

[cmap]
c1 = "PuBu"
c2 = "OrRd"

[subplots_adjust.kw]
left = 0.1
right = 0.95
bottom = 0.1
top = 0.95
wspace = 0.5

[save.kw]
transparent = true

[quantiles]
sigma = 0.68

[quantiles.kw]
c = 'k'
lw = 1
# ls = [[0], [5, 7]  # loosely_dashed

[label]
pad = 5

[gridspec.bandplot]
ratio = [1.0, 0.3]

